import React from 'react';

import type { Metadata } from 'next';
import { Cabin } from 'next/font/google';
import '../styles/globals.css';

const cabinSans = Cabin({
  variable: '--font-cabin',
  subsets: ['latin'],
});

// TODO change metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cabinSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
